---
- name: fail if no username or password provided
  ansible.builtin.fail: msg="username and password required as playbook input"
  when: username is undefined or password is undefined or connector.larPublicKey.encodedKey is undefined

- script: "load_modules.py"

- script: "encrypt.py {{ username | regex_escape() }} {{ password | regex_escape() }} {{ connector.larPublicKey.encodedKey }}"
  register: encrypted_creds

- name: Parse python script output
  ansible.builtin.set_fact:
    credentials: "{{ encrypted_creds.stdout | from_json }}"

- name: Add public key id to the encrypted payload
  ansible.builtin.set_fact:
    credentials: "{{ credentials | combine({'keyId': connector.larPublicKey.keyId}) }}"
