galaxy_info:
  author: Aaron Hackney
  description: Simple role to take a CDO region, endpoint, and payload and perform an HTTP POST call
  company: Cisco Systems Inc.
  license: MIT

  min_ansible_version: 2.1

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  # platforms:
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags:
    - cdo
    - cdfmc
    - asa

dependencies: []

