---
- name: Get specific device details and retry until stateMachineInstanceCondition is DONE
  vars:
    relative_path: "/aegis/rest/v1/device/{{uid}}/specific-device"
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{api_key}}"
    url: "https://{{cdo_region}}{{relative_path}}"
    method: "GET"
  until: "{{specific_device.json.stateMachineDetails.stateMachineInstanceCondition}} == 'DONE'"
  retries: "{{api_retries if api_retries is defined else 1}}"
  delay: "{{api_delay if api_delay is defined else 2}}"
  register: specific_device_state
