---
- name: Get connector (SDC/SEC/CloudSDC) based on name
  vars:
    relative_path: "/aegis/rest/v1/services/targets/proxies"
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{api_key}}"
    url: "https://{{cdo_region}}{{relative_path}}"
    method: "GET"
    return_content: false
  register: proxies

- name: Get specfic SDC based on the SDC/CDG/SEC name (lar_name input paramter)
  vars:
    lar_query: "json[?name==`{{ search_lar_name }}`]"

  set_fact:
    connector_list: "{{ proxies | json_query(lar_query) }}"

- name: Fail if connector was not found
  ansible.builtin.fail: msg="CDG/SDC {{lar_name}} was not found"
  when: "connector_list | length < 1"

- name: Extract connector from connector_list
  set_fact:
    connector: "{{connector_list[0]}}"

- name: debug get connector
  ansible.builtin.debug: var=connector
  when: play_debug == true
