---
# licenses: list of BASE and then optionally THREAT,URLFilter,MALWARE,VPNOnly,PLUS,APEX,PLUS,APEX
# is_virtual: true if virtual default false (optional)
# performance_tier: only one of the following [FTDv5|FTDv10|FTDv20|FTDv30|FTDv50|FTDv100|FTDv]

devices:
  # - tenant: CDO_cisco_aahackne
  #   cdo_region: www.defenseorchestrator.com
  #   device_name: Austin
  #   ip_address: 172.30.4.101
  #   port: 8443
  #   lar_name: CDO_cisco_aahackne-SDC-1
  #   username: cisco
  #   password: P@$$w0rd1!
  #   device_type: ASA
  # - tenant: CDO_cisco_aahackne
  #   cdo_region: www.defenseorchestrator.com
  #   device_name: SanAntonio
  #   ip_address: 172.30.4.102
  #   port: 8443
  #   lar_name: CDO_cisco_aahackne-SDC-1
  #   username: cisco
  #   password: P@$$w0rd1!
  #   device_type: ASA

  - tenant: CDO_Aaron_Hackney_Lab__Cisco
    cdo_region: www.defenseorchestrator.com
    device_name: Houston
    ip_address: 172.30.4.203
    port: 8443
    lar_name: CDO_Aaron_Hackney_Lab__Cisco-SDC-1
    username: cisco
    password: P@$$w0rd1!
    device_type: ASA

  - tenant: CDO_Aaron_Hackney_Lab__Cisco
    cdo_region: www.defenseorchestrator.com
    device_name: Dallas
    onboard_method: cli
    access_control_policy: SanAntonio
    licenses:
      - BASE
      - THREAT
      - URLFilter
      - MALWARE
      - PLUS
    device_type: FTD

  # - tenant: CDO_Aaron_Hackney_Lab__Cisco
  #   cdo_region: www.defenseorchestrator.com
  #   device_name: ElPaso
  #   onboard_method: ltp
  #   serial_number: abc12345
  #   access_control_policy: Default Access Control Policy
  #   licenses:
  #     - BASE
  #     - THREAT
  #     - URLFilter
  #     - MALWARE
  #     - VPNOnly
  #   device_type: FTD
