---
- name: Add Devices to CDO
  become: false
  hosts: all
  connection: local

  tasks:
    ###########################################################################
    # Get date range and other search terms from from host varaibles
    - name: Get this devices settings from host varaibles
      ansible.builtin.set_fact:
        # api_key: from group_vars
        # cdo_region: from group_vars
        # If no end date assume *
        # 2022-01-01T00:00:00-05:00
        # 2022-01-01T00:00:00-05:00
        # Get these paraneters from host_vars
        # (timestamp:[ fromdate TO todate ])
        # AND (DeviceType:devicetype)
        # AND (evrntype)
        # q: search-string
        # s: filter (policy protocol sensorid, etc)
        # post /swc/v1/historical/{{search_string}}
        # work with file looping....
        # save results as a file....
        start_date: xxx
        end_date: xxx
        source_ip: xxx
        dest_ip: xxx
        dest_port: xxx
        event_type: xxx
        sensor_id: xxx
        protocol: xxx
        job_name: xxx
        device_type: xxx
        api_limit: 100
        firewall_policy: xxx
        action: xxx
        

        
      
