---
- name: Get CDO devices
  vars:
    relative_path: "/aegis/rest/v1/services/targets/devices{{api_query}}"
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{api_key}}"
    url: "https://{{cdo_region}}{{relative_path}}"
    method: "GET"
  register: device_data

- name: debug cdo_get_devices
  ansible.builtin.debug: msg="device data {{device_data}}"
  when: play_debug == true
